version: '3.8'

services:
  event-producer:
    build: ./producer
    env_file:
      - .env
    depends_on:
      - event-registry

  event-processor:
    build: ./consumer
    env_file:
      - .env

  event-registry:
    build: ./registry
    env_file:
      - .env
    ports:
      - "3000:3000"

